name: security

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  # Static security scan using gosec
  # https://github.com/securego/gosec
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
  TruffleHog:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: TruffleHog OSS
          id: trufflehog
          uses: trufflesecurity/trufflehog@main
          continue-on-error: true
          with:
            path: ./
            base: "${{ github.event.repository.default_branch }}"
            head: HEAD
            extra_args: --debug
        - name: Scan Results Status
          if: steps.trufflehog.outcome == 'failure'
          run: exit 1
